name: Ubuntu
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOFLAGS: '-trimpath -mod=readonly'
      GO111MODULE: 'on'
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.15.x
        goos:
          - linux
        goarch:
          - amd64
          - arm
          - arm64
        main:
          - genji
          - genji/fuzz
          - genji/cmd/genji
          - genji/engine/badgerengine
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set up environment
        uses: actions/github-script@v3
        with:
          script: |
            const { spawn } = require('child_process')

            // Set -race flag for supported targets.
            switch (process.env.GOARCH) {
            case 'amd64':
            case 'ppc64le':
            case 'arm64':
              core.exportVariable('GOFLAGS', `${process.env.GOFLAGS} -race`)
              core.exportVariable('CGO_ENABLED', '1')
              break
            default:
              core.exportVariable('CGO_ENABLED', '0')
              core.exportVariable('GO_EXTLINK_ENABLED', '0')
              break
            }

            // Install QEMU and GCC cross compiler. We only need that for -race flag.
            const apt = ['apt-get', 'install', '-y', '--no-install-recommends']
            apt.push('qemu-user')
            apt.push('qemu-user-binfmt')
            switch (process.env.GOARCH) {
            case 'arm':
              break
            case 'arm64':
              apt.push('gcc-aarch64-linux-gnu')
              core.exportVariable('CC', 'aarch64-linux-gnu-gcc')
              core.exportVariable('PKG_CONFIG_PATH', '/usr/lib/aarch64-linux-gnu/pkgconfig')
              break
            default:
              return
            }
            const rc = await spawn('sudo', apt, { stdio: 'inherit' })
            if (rc.status || rc.error) {
              process.exit(1)
            }

      - name: Get cache path
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: modcache

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.modcache.outputs.dir }}
          key: modcache-${{ matrix.goos }}-${{ matrix.goarch }}-${{ hashFiles('**/go.sum') }}
          restore-keys: modcache-

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: genji

      - name: Checkout corpus
        uses: actions/checkout@v2
        with:
          repository: genjidb/go-fuzz-corpus
          path: genji/fuzz/testdata/fuzz

      - name: Download dependencies
        run: go mod download
        working-directory: ${{ matrix.main }}

      - name: Run tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic -timeout=2m ./...
        working-directory: ${{ matrix.main }}

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          directory: ${{ matrix.main }}
